name: Unit testing with coverage (master)

on:
  push:
    branches: [ master ]

env:
  LINE_COV_GATE: 70
  MCDC_COV_GATE: 30

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build:
    runs-on: self-hosted
    continue-on-error: true

    steps:
    - uses: actions/checkout@v2

    - name: Configure CMake
      shell: bash
      working-directory: ${{github.workspace}}
      run: cmake -DCPPTEST_COVERAGE=ON -S . -B .build
  